language: c++
compiler:
    - gcc
os:
    - linux
env:
    - CFLAGS=-fprofile-arcs -ftestcoverage
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
install:
    - pip install cpp-coveralls
    - ./setup.sh
script:
    - cd build
    - make -j2 liblw-tests
    - Default/liblw-tests
after_success:
    - coveralls --exclude tests --exclude external
