language: c++
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - gcc-5
            - g++-5
env:
    - CC=gcc-4.9 CXX=g++-4.9
    - CC=gcc-5 CXX=g++-5
install:
    - ./setup.sh
script:
    - cd build
    - make -j2 liblw-tests
    - Default/liblw-tests
