language: c++
compiler:
  - gcc
os:
  - linux
dist: bionic
addons:
  apt:
    packages:
      - binutils
      - lcov
install:
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -y install gcc-9 g++-9 openjdk-8-jdk bazel
  - sudo update-alternatives --install /usr/bin/g++ g++ `which g++-9` 30
  - sudo update-alternatives --install /usr/bin/gcc gcc `which gcc-9` 30
script:
  - bazel test //...
# after_success:
#   - cd $TRAVIS_BUILD_DIR
#   - coveralls --exclude external --exclude tests --root $TRAVIS_BUILD_DIR --build-root $TRAVIS_BUILD_DIR/build --gcov gcov-5 --gcov-options '\-lp'
