language: c++
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r/test
        packages:
            - gcc-4.9
            - g++-4.9
install:
    - ./setup.sh
script:
    - cd build
    - make -j2 liblw-tests
    - Default/liblw-tests
