language: c++
compiler:
    - gcc
os:
    - linux
env:
    - CFLAGS="-coverage -g -O0"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - lcov
install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install cpp-coveralls --user `whoami`
    - ./setup.sh --coverage
script:
    - cd build
    - make -j2 liblw-tests
    - Default/liblw-tests
after_success:
    - coveralls --exclude tests --exclude external
